version: 0.1

environment_variables:
  plaintext:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - npm install yarn -g
  pre_build:
    commands:
      - echo install started on `date`
      - npm install
  build:
    commands:
      - echo test started on `date`
      - npm test
  post_build:
    commands:
      - echo build started on `date`
      - npm run build
artifacts:
  files:
    - public/*